language: node_js

notifications:
    email: false

cache:
    yarn: true
    directories:
        - node_modules
        - /home/travis/.pnpm-store

before_install:
  - npm install -g yarn
  - npm install -g create-cycle-app
  - npm install -g pnpm@^2.17.0

matrix:
    include:
        - script: ./runCI.sh yarn
          node_js: 6
          install: yarn install
        - script: ./runCI.sh yarn
          node_js: 8
          install: yarn install
#       - script: ./runCI.sh pnpm
#         node_js: 6
#         install: pnpm install
#       - script: ./runCI.sh pnpm
#         node_js: 8
#         install: pnpm install
